name: check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [canary]

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - run: deno task lint && git diff-index --quiet HEAD
      - run: deno task fmt && git diff-index --quiet HEAD
